name: Java CI with Maven for PR on Windows

on:
  push:
  pull_request:
  
jobs:
  build:
    # specific version of Windows server, to avoid the error
    # "The container operating system does not match the host operating system"
    runs-on: windows-2019
    env:
      DOCKER_HOST: tcp://localhost:2375
        
    name: Build with Java 11 on Windows
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-    
    - name: Docker config
      run: >
        sc config docker
        binpath="dockerd.exe -- run-service -H tcp://localhost:2375"
    - name: Docker restart
      run: docker info        
    - name: Build with Maven
      run: mvn verify -Pskip-testcontainers
      working-directory: library      